In [40]:
import pandas as pd
import numpy as np
import pickle
import os
df_prices=pd.read_csv('data_deep_learning/open_prices.csv', index_col=0)
targets = np.load('data_deep_learning/targets', allow_pickle=True)

In [1]:
cols = list(df_prices.columns)
names = ["BTC/USDT","NEIRO/USDT","1000PEPE/USDT","ETH/USDT","REEF/USDT","SOL/USDT","NEIROETH/USDT","HMSTR/USDT","CATI/USDT","UXLINK/USDT","DOGS/USDT","1MBABYDOGE/USDT","1000SHIB/USDT","BIGTIME/USDT","POPCAT/USDT","BNB/USDT","SUI/USDT","WIF/USDT","XRP/USDT","1000FLOKI/USDT","1000BONK/USDT","TON/USDT","TURBO/USDT","1000RATS/USDT","MEW/USDT","FET/USDT","DOGE/USDT","1000SATS/USDT","ZETA/USDT","ONDO/USDT"]
dic_names


30


In [ ]:
series_f64=df_prices.notna().idxmax().sort_values()
nans_per_i=[ sum([np.isnan(k) for k in targets[:, i]]) for i in range(targets.shape[1])]
n_list = [(i,int(val)) for i, val in enumerate(nans_per_i)]
andidates1=sorted(n_list, key = lambda x:x[1])[:100]



In [15]:
cols=list(df_prices.columns)
c_series=[(i, j) for i,j in andidates1 if cols[i] in series_f64[:64]]

In [ ]:
names = ["BTC/USDT","NEIRO/USDT","1000PEPE/USDT","ETH/USDT","REEF/USDT","SOL/USDT","NEIROETH/USDT","HMSTR/USDT","CATI/USDT","UXLINK/USDT","DOGS/USDT","1MBABYDOGE/USDT","1000SHIB/USDT","BIGTIME/USDT","POPCAT/USDT","BNB/USDT","SUI/USDT","WIF/USDT","XRP/USDT","1000FLOKI/USDT","1000BONK/USDT","TON/USDT","TURBO/USDT","1000RATS/USDT","MEW/USDT","FET/USDT","DOGE/USDT","1000SATS/USDT","ZETA/USDT","ONDO/USDT"
]
n_names=[ v for v in enumerate(cols) if v[1] in names]
n_dic_2 = {}
#have prices up to the last timestamp
for i in range(len(n_names)):
    if np.isnan(df_prices[n_names[i][1]].iloc[-1]):
        print("Miss last price at ", n_names[i][1])
count = 0       
#need to find where the last nan is located!! 
tolerance = 100
for i in range(len(n_names)):
    for j in range(1, 1000):
        if not np.isnan(targets[-j,n_names[i][0]]):
            add =  1
            while  not np.isnan(targets[-(j + add),n_names[i][0]]) and add < tolerance:
                add +=1
            if add == tolerance:
                n_dic_2[n_names[i][1]]={
                    'index': n_names[i][0],
                    'top_i': j
                }  
                break 
            else:
                print( " there are more nan's at ",n_names[i][1], " smaller than -",j)    
            
print(count)        
##check if at those indices there are more nans
#checking if assigning a bibber tolerance gives different top_i values, it does not, tol of 40 if fine
[ (k, val) for k, val in n_dic.items() if val['top_i'] != n_dic_2[k]['top_i']]

# for k, val in n_dic.items():
#     for i in range(-val['top_i'], 100):
#         if np.isnan(targets[-i,val['index']]):
#             print(f" Careful, something to check at {k} at index -{i}")
#             break

In [1]:
#import json
# with open ("dic_30_series.json", "w") as f:
#     json.dump(n_dic, f)
import pickle
with open('/Users/carlos/Documents/Peccala/deepL_tests/input_log_rets.pkl', 'rb') as file:
   log_rets = pickle.load(file)

In [5]:
import json
path0="few_series/"
with open(path0+"dic_np_saved_series.json", 'r') as file:
    dic_s = json.load(file) 
len(dic_s)    

21

In [6]:
dic ={"1000BONK/USDT": {"index": 1, "top_i": 11}, "1000FLOKI/USDT": {"index": 5, "top_i": 13}, "1000PEPE/USDT": {"index": 7, "top_i": 12}, "1000RATS/USDT": {"index": 8, "top_i": 8}, "1000SATS/USDT": {"index": 9, "top_i": 13}, "1000SHIB/USDT": {"index": 10, "top_i": 15}, "BIGTIME/USDT": {"index": 65, "top_i": 13}, "BNB/USDT": {"index": 68, "top_i": 15}, "BTC/USDT": {"index": 77, "top_i": 30}, "DOGE/USDT": {"index": 113, "top_i": 13}, "ETH/USDT": {"index": 130, "top_i": 125}, "FET/USDT": {"index": 131, "top_i": 13}, "MEW/USDT": {"index": 214, "top_i": 25}, "ONDO/USDT": {"index": 237, "top_i": 12}, "REEF/USDT": {"index": 265, "top_i": 13}, "SOL/USDT": {"index": 293, "top_i": 15}, "SUI/USDT": {"index": 305, "top_i": 7}, "TURBO/USDT": {"index": 325, "top_i": 12}, "WIF/USDT": {"index": 339, "top_i": 12}, "XRP/USDT": {"index": 347, "top_i": 9}, "ZETA/USDT": {"index": 356, "top_i": 13}}
print(dic.keys())


dict_keys(['1000BONK/USDT', '1000FLOKI/USDT', '1000PEPE/USDT', '1000RATS/USDT', '1000SATS/USDT', '1000SHIB/USDT', 'BIGTIME/USDT', 'BNB/USDT', 'BTC/USDT', 'DOGE/USDT', 'ETH/USDT', 'FET/USDT', 'MEW/USDT', 'ONDO/USDT', 'REEF/USDT', 'SOL/USDT', 'SUI/USDT', 'TURBO/USDT', 'WIF/USDT', 'XRP/USDT', 'ZETA/USDT'])


In [9]:
# import pickle
# with open('/Users/carlos/Documents/Peccala/deepL_tests/deep_learning/input_histograms.pkl', 'rb') as file:
#    histograms = pickle.load(file)
hist_2_keep = { key: histograms[key] for key in dic_s}   

In [25]:
# for key in hist_2_keep:
#     k=key
#     arr_ex = hist_2_keep[key][-6000 : -dic_s[k]['top_i']]
#     hist_2_keep[key] = arr_ex
# import numpy as np
# np_aux = np.load('/Users/carlos/Documents/Peccala/deepL_tests/few_series/np_series_concat.npy')
np_aux.shape[1]

5875

In [39]:
# np_aux_f=np.array([np.hstack([hist_2_keep[val][-np_aux.shape[1]:], np_aux[i,:,:]]) for i, val in enumerate(hist_2_keep.keys())])
# np_aux_f.shape
#np.save('/Users/carlos/Documents/Peccala/deepL_tests/few_series/np_series_concat2.npy', np_aux_f)
for i in range(int(np_aux_f.shape[0])):
    x = np_aux_f[i,:,:]
    if np.isnan(x).any().any():
        print(i , " has nans")

12  has nans
13  has nans
17  has nans
18  has nans
20  has nans


In [20]:
for k, val in hist_2_keep.items():
    print(val.shape)

(5989, 72)
(5987, 72)
(5988, 72)
(5992, 72)
(5987, 72)
(5985, 72)
(5987, 72)
(5985, 72)
(5970, 72)
(5987, 72)
(5875, 72)
(5987, 72)
(5975, 72)
(5988, 72)
(5987, 72)
(5985, 72)
(5993, 72)
(5988, 72)
(5988, 72)
(5991, 72)
(5987, 72)


In [ ]:
import numpy as np
n_dic={"1000BONK/USDT": {"index": 1, "top_i": 11}, "1000FLOKI/USDT": {"index": 5, "top_i": 13}, "1000PEPE/USDT": {"index": 7, "top_i": 12}, "1000RATS/USDT": {"index": 8, "top_i": 8}, "1000SATS/USDT": {"index": 9, "top_i": 13}, "1000SHIB/USDT": {"index": 10, "top_i": 15}, "1MBABYDOGE/USDT": {"index": 15, "top_i": 12}, "BIGTIME/USDT": {"index": 65, "top_i": 13}, "BNB/USDT": {"index": 68, "top_i": 15}, "BTC/USDT": {"index": 77, "top_i": 30}, "CATI/USDT": {"index": 83, "top_i": 13}, "DOGE/USDT": {"index": 113, "top_i": 13}, "DOGS/USDT": {"index": 114, "top_i": 13}, "ETH/USDT": {"index": 130, "top_i": 125}, "FET/USDT": {"index": 131, "top_i": 13}, "HMSTR/USDT": {"index": 160, "top_i": 13}, "MEW/USDT": {"index": 214, "top_i": 25}, "NEIROETH/USDT": {"index": 222, "top_i": 13}, "NEIRO/USDT": {"index": 223, "top_i": 13}, "ONDO/USDT": {"index": 237, "top_i": 12}, "POPCAT/USDT": {"index": 254, "top_i": 13}, "REEF/USDT": {"index": 265, "top_i": 13}, "SOL/USDT": {"index": 293, "top_i": 15}, "SUI/USDT": {"index": 305, "top_i": 7}, "TON/USDT": {"index": 320, "top_i": 13}, "TURBO/USDT": {"index": 325, "top_i": 12}, "UXLINK/USDT": {"index": 332, "top_i": 13}, "WIF/USDT": {"index": 339, "top_i": 12}, "XRP/USDT": {"index": 347, "top_i": 9}, "ZETA/USDT": {"index": 356, "top_i": 13}}
#np_rets = [log_rets[key][-6000 :-n_dic[key]["top_i"]] for key in n_dic ]
[k for i, k in enumerate(n_dic.keys()) if i in [6, 10 ,12, 15, 17, 18, 20, 24, 26]]

['1MBABYDOGE/USDT',
 'CATI/USDT',
 'DOGS/USDT',
 'HMSTR/USDT',
 'NEIROETH/USDT',
 'NEIRO/USDT',
 'POPCAT/USDT',
 'TON/USDT',
 'UXLINK/USDT']

In [33]:
# for j, arr in enumerate(np_rets):
#     for i,k in enumerate(arr):
#         if i> len(arr) - 3032 and np.isnan(k).any():
#             print("Nans at ", i, " in item ", j)
#             break
# forbid =  ['1MBABYDOGE/USDT','CATI/USDT','DOGS/USDT','HMSTR/USDT','NEIROETH/USDT','NEIRO/USDT','POPCAT/USDT','TON/USDT','UXLINK/USDT']       
# n_dic={"1000BONK/USDT": {"index": 1, "top_i": 11}, "1000FLOKI/USDT": {"index": 5, "top_i": 13}, "1000PEPE/USDT": {"index": 7, "top_i": 12}, "1000RATS/USDT": {"index": 8, "top_i": 8}, "1000SATS/USDT": {"index": 9, "top_i": 13}, "1000SHIB/USDT": {"index": 10, "top_i": 15}, "1MBABYDOGE/USDT": {"index": 15, "top_i": 12}, "BIGTIME/USDT": {"index": 65, "top_i": 13}, "BNB/USDT": {"index": 68, "top_i": 15}, "BTC/USDT": {"index": 77, "top_i": 30}, "CATI/USDT": {"index": 83, "top_i": 13}, "DOGE/USDT": {"index": 113, "top_i": 13}, "DOGS/USDT": {"index": 114, "top_i": 13}, "ETH/USDT": {"index": 130, "top_i": 125}, "FET/USDT": {"index": 131, "top_i": 13}, "HMSTR/USDT": {"index": 160, "top_i": 13}, "MEW/USDT": {"index": 214, "top_i": 25}, "NEIROETH/USDT": {"index": 222, "top_i": 13}, "NEIRO/USDT": {"index": 223, "top_i": 13}, "ONDO/USDT": {"index": 237, "top_i": 12}, "POPCAT/USDT": {"index": 254, "top_i": 13}, "REEF/USDT": {"index": 265, "top_i": 13}, "SOL/USDT": {"index": 293, "top_i": 15}, "SUI/USDT": {"index": 305, "top_i": 7}, "TON/USDT": {"index": 320, "top_i": 13}, "TURBO/USDT": {"index": 325, "top_i": 12}, "UXLINK/USDT": {"index": 332, "top_i": 13}, "WIF/USDT": {"index": 339, "top_i": 12}, "XRP/USDT": {"index": 347, "top_i": 9}, "ZETA/USDT": {"index": 356, "top_i": 13}}
# n_dic = {k : n_dic[k] for k in n_dic if not k in forbid} 
n_arr = [k for i, k in enumerate(np_rets) if i not in [6, 10 ,12, 15, 17, 18, 20, 24, 26]]
len(n_arr)

21

In [37]:
n_arr[0][0].shape
     

(72,)

In [44]:
targets[-(n_dic['1000BONK/USDT']['top_i'] -1), n_dic['1000BONK/USDT']['index']]

nan

In [ ]:
n_list = [(i,int(val)) for i, val in enumerate(nans_per_i)]
len(names)
dic_s_i= {}
for i,_ in c_series:

    key = cols[i]
    dic_s_i[key]={"i_target":i}
    aux_series = targets[:,i]
    l_i=0
    for j, val in enumerate(aux_series):
        if not np.isnan(val) and not np.isnan(df_prices[key].iloc[j]):
            dic_s_i[key]["lower_target_i"]=j
            l_i=j
            break
    for j in range(aux_series.shape[0] -1, 0, -1) :
        if not np.isnan(sum(targets[l_i:j+1, i]))  and not np.isnan(df_prices[key].iloc[j]):
            dic_s_i[key]['upper_target_i']=j
            break
    

#dic_s_i is the dictionary to index the series with the corresp. position in the target np array

In [ ]:
for i, key in enumerate(n_dic.keys()):
    target_s = targets[:-n_dic[key]["top_i"], n_dic[key]["index"]]
    prices_s = df_prices[key][:-n_dic[key]["top_i"]]
    target_s=target_s[-n_arr[i].shape[0]:]
    prices_s=prices_s[-n_arr[i].shape[0]:]
    # if target_s.shape[0] != n_arr[i].shape[0]:
    #     print("mismatch target at ", key)
    # if prices_s.shape[0] != n_arr[i].shape[0]:
    #     print("mismatch price shape at ", key) 
    resulting_series = np.array([np.hstack([orig, add1, add2]) for orig, add1, add2 in zip(n_arr[i], prices_s, target_s)])

# Check the shape of the first element
   
    n_arr[i]=resulting_series
   
    # print(f"for key {key}")
    # print(f" have corresp shapes {target_s.shape} and {prices_s.shape} ")
    # print(f" and types {type(target_s)} and {type(prices_s)}")
    # print(f"the one to match has shape {n_arr[0].shape}")
    # break


In [63]:
len(n_dic)-np_arr_series.shape[0]

0

In [64]:
#np_arr_series = np.array([n[-5875:,:] for n in n_arr])
#np_arr_series.shape
import json
with open ("few_series/dic_np_saved_series.json", "w") as f:
    json.dump(n_dic, f)
np.save("few_series/np_series_concat", np_arr_series)    

In [7]:
dic={"1000BONK/USDT": {"index": 1, "top_i": 11}, "1000FLOKI/USDT": {"index": 5, "top_i": 13}, "1000PEPE/USDT": {"index": 7, "top_i": 12}, "1000RATS/USDT": {"index": 8, "top_i": 8}, "1000SATS/USDT": {"index": 9, "top_i": 13}, "1000SHIB/USDT": {"index": 10, "top_i": 15}, "BIGTIME/USDT": {"index": 65, "top_i": 13}, "BNB/USDT": {"index": 68, "top_i": 15}, "BTC/USDT": {"index": 77, "top_i": 30}, "DOGE/USDT": {"index": 113, "top_i": 13}, "ETH/USDT": {"index": 130, "top_i": 125}, "FET/USDT": {"index": 131, "top_i": 13}, "MEW/USDT": {"index": 214, "top_i": 25}, "ONDO/USDT": {"index": 237, "top_i": 12}, "REEF/USDT": {"index": 265, "top_i": 13}, "SOL/USDT": {"index": 293, "top_i": 15}, "SUI/USDT": {"index": 305, "top_i": 7}, "TURBO/USDT": {"index": 325, "top_i": 12}, "WIF/USDT": {"index": 339, "top_i": 12}, "XRP/USDT": {"index": 347, "top_i": 9}, "ZETA/USDT": {"index": 356, "top_i": 13}}
print(len(dic))

print(dic.keys())

21
dict_keys(['1000BONK/USDT', '1000FLOKI/USDT', '1000PEPE/USDT', '1000RATS/USDT', '1000SATS/USDT', '1000SHIB/USDT', 'BIGTIME/USDT', 'BNB/USDT', 'BTC/USDT', 'DOGE/USDT', 'ETH/USDT', 'FET/USDT', 'MEW/USDT', 'ONDO/USDT', 'REEF/USDT', 'SOL/USDT', 'SUI/USDT', 'TURBO/USDT', 'WIF/USDT', 'XRP/USDT', 'ZETA/USDT'])


In [19]:
import pickle
with open('/Users/carlos/Documents/Peccala/deepL_tests/input_log_rets.pkl', 'rb') as file:
   log_rets = pickle.load(file)
#with open('/Users/carlos/Documents/Peccala/deepL_tests/data_deep_learning/input_histograms.pkl') as file:
 #   hist = pickle.load(file)

updates = 0
for key in dic_s_i:
   for j in range(dic_s_i[key]['lower_target_i'], len(log_rets[key])):
      if sum([ np.isnan(k) for k in log_rets[key][j]]) == 0:
         if dic_s_i[key]['lower_target_i'] < j:
            dic_s_i[key]['lower_target_i']=j 
            updates +=1
            #print(f"an l-update at {key}")
         break
   for j in range(len(log_rets[key])-1, 0, -1):
      if sum([ np.isnan(k) for k in log_rets[key][j]]) == 0:
         if dic_s_i[key]['upper_target_i'] >j:
            dic_s_i[key]['upper_target_i'] =j
            print(f"an u-update at {key}")
            updates +=1
         break   

/var/folders/0f/11hy697j7mv487fs334bjwvr0000gp/T/ipykernel_4987/2455240514.py:3: DeprecationWarning: numpy.core.numeric is deprecated and has been renamed to numpy._core.numeric. The numpy._core namespace contains private NumPy internals and its use is discouraged, as NumPy internals can change without warning in any release. In practice, most real-world usage of numpy.core is to access functionality in the public NumPy API. If that is the case, use the public NumPy API. If not, you are using NumPy internals. If you would still like to access an internal attribute, use numpy._core.numeric._frombuffer.
  log_rets = pickle.load(file)


In [ ]:
directory_path = "data_deep_learning/series_data/"
for key in dic_s_i:
    ind = dic_s_i[key]['i_target']
    l_i = dic_s_i[key]['lower_target_i']
    u_i = dic_s_i[key]['upper_target_i']
    rets = log_rets[key]
    f_name = key.replace('/','&')
    aux_np=np.column_stack((rets[l_i:u_i, :],  df_prices[key][l_i: u_i], targets[l_i: u_i, ind]))
    np.save(directory_path+f_name+'.npy', aux_np)



[]

In [1]:
import pickle
with open('/Users/carlos/Documents/Peccala/deepL_tests/data_deep_learning/input_histograms.pkl', 'rb') as file:
    hist = pickle.load(file)

/var/folders/0f/11hy697j7mv487fs334bjwvr0000gp/T/ipykernel_7694/3503708678.py:3: DeprecationWarning: numpy.core.numeric is deprecated and has been renamed to numpy._core.numeric. The numpy._core namespace contains private NumPy internals and its use is discouraged, as NumPy internals can change without warning in any release. In practice, most real-world usage of numpy.core is to access functionality in the public NumPy API. If that is the case, use the public NumPy API. If not, you are using NumPy internals. If you would still like to access an internal attribute, use numpy._core.numeric._frombuffer.
  hist = pickle.load(file)


In [6]:
del df_prices
del targets
del log_rets

In [2]:
import json
#with open ("dic_series.json", "w") as f:
 #   json.dump(dic_s_i, f)
with open("dic_series.json", 'r') as file:
    dic_s = json.load(file)    
    

In [5]:
import os
import numpy as np

# Define the directory containing the .npy files
directory_path = "data_deep_learning/series_data"

for file_name in os.listdir(directory_path):
    if file_name.endswith(".npy"):  
        key = file_name.split('.')[0].replace("&","/")
        print("for the key" ,key)

        data = np.load(directory_path+"/"+file_name)
        aux_h = hist[key]
        l_i = dic_s[key]["lower_target_i"]
        u_i = dic_s[key]["upper_target_i"]
        print("old shape",data.shape)
        print("n shape", aux_h[l_i:u_i, :].shape)
        n_arr = np.concatenate((aux_h[l_i:u_i, :], data), axis=1)
        print("result s ",n_arr.shape)

        
        # Save the modified data back to the file
        np.save(directory_path+"/"+file_name, n_arr)


for the key DUSK/USDT
old shape (46825, 74)
n shape (46825, 72)
result s  (46825, 146)
for the key XMR/USDT
old shape (49914, 74)
n shape (49914, 72)
result s  (49914, 146)
for the key MATIC/USDT
old shape (46945, 74)
n shape (46945, 72)
result s  (46945, 146)
for the key HOT/USDT
old shape (50519, 74)
n shape (50519, 72)
result s  (50519, 146)
for the key DOGE/USDT
old shape (47230, 74)
n shape (47230, 72)
result s  (47230, 146)
for the key BAND/USDT
old shape (45430, 74)
n shape (45430, 72)
result s  (45430, 146)
for the key LINK/USDT
old shape (51310, 74)
n shape (51310, 72)
result s  (51310, 146)
for the key REN/USDT
old shape (45272, 74)
n shape (45272, 72)
result s  (45272, 146)
for the key WAVES/USDT
old shape (47368, 74)
n shape (47368, 72)
result s  (47368, 146)
for the key CVC/USDT
old shape (44837, 74)
n shape (44837, 72)
result s  (44837, 146)
for the key ZRX/USDT
old shape (50297, 74)
n shape (50297, 72)
result s  (50297, 146)
for the key IOTX/USDT
old shape (44071, 74)
n 

In [98]:
mini = 700000000
min_key = "nada"
for key in dic_s_i:
    series_key = targets[:,dic_s_i[key]]
    s_not_nans = sum(not np.isnan(x) for x in series_key)
    if s_not_nans < mini:
        mini = s_not_nans
        min_key = key

In [14]:
import numpy as np
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(np.array([arr[2,:], arr[0,:], arr[1,:]]))

[[7 8 9]
 [1 2 3]
 [4 5 6]]


In [18]:
import random
l = [i for i in range(9)]
random.shuffle(l)
print(l)

[4, 6, 2, 8, 7, 5, 0, 3, 1]


In [106]:
min_series = targets[:,dic_s_i[min_key]]
for i, val in enumerate(min_series):
    if not np.isnan(val):
        print(f"lower not nan ind {i}")
        break
for i in range(len(min_series) -1, 0, -1):
    if not np.isnan(min_series[i]):
        print(f"max not nan ind {i}")
        break

lower not nan ind 12774
max not nan ind 38731


In [ ]:
for i in min_series[12774:38732]:
    if np.isnan(i):
        print("an error!! ")

In [ ]:
#hist_btc=df_hist['BTC/USDT']
##index of interest possibly 'BTC/USDT'
##from index  2376 on the matrices in hist_btc have all of those indices
##there are targets from index 0 up to -30 the last 29 records have NaNs
target_prices = df_prices['BTC/USDT']

for i in range(df_prices.shape[1]):
    if df_prices.columns[i] == "BTC/USDT":
        print("Found it at", i)
        ind = i
#the found index is ahead by 1 because the first col is 'Unamed: 0', is the ts
targets = np.load(pre_path + 'targets', allow_pickle=True)
target_btc=targets[:,ind -1]   

#del df_hist
del df_prices
del targets

In [ ]:
#find first index where there's no NaNs in its corresp matrix
for ind, val in enumerate(btc_rets):
    if not np.isnan(val.sum()):
        found = ind
        print(f"There is something in index {ind}")
        break
#check that the elems from there on have no NaNs    
for i in range(found, len(btc_rets)):
    if np.isnan(btc_rets[i].sum()):
        print("There are missing elements!!")   

In [ ]:
#look starting at the end where are not NaNs in the target
for i in range(1,10000):
    if not np.isnan(target_btc[-i]):
        ind2 = i
        print(f"Not an NaN at -{i}")
        break
#filter data to start from step 2376 up to -30
found = 2376
#target_btc_f = target_btc[found:-ind2 + 1]
target_prices_f = target_prices[found:-ind2 + 1]
btc_rets_f = btc_rets[found:-ind2 + 1]
  

In [23]:
data = np.load('data.npy')
ndata = np.array([np.concatenate((i, z)) for i, z in zip(data, btc_rets_f)])
ndata.shape
#np.save('with_rets_data.npy', ndata)
#np.save('tarbet.npy', target_btc_f)

(61406, 145)

In [25]:
os.getcwd()

'/Users/carlos/Documents/Peccala/deepL_tests'

In [ ]:
def create_seq_from_ts(data, seq_length):
    """
    Function that returns the vectors with corresponding seq_length,
    of observations in the past.
    Output should have shape (data.shape[0] - seq_length, seq_length, num_features)
    
    """
    sequences = []
    
    for i in range(len(data) - seq_length + 1):
        # Extract the sequence of features
        sequence = data[i:i+seq_length]
        sequences.append(sequence)
    
    sequences = np.array(sequences)
    
    return sequences

# Example usage

seq_length = 7

data = np.array([np.concatenate(([i], z)) for i, z in zip(target_prices_f, hist_btc_f)])


sequences = create_seq_from_ts(data, seq_length)
print("seq shape", sequences.shape) 

In [ ]:
import torch
print("seq shap",sequences.shape)
print("labels shape", target_btc_f[seq_length-1:].shape)

test_percentage = 0.13
test_l = int(sequences.shape[0]*test_percentage)
X_tr = torch.Tensor(sequences[:-test_l,:,:])
y_tr = torch.Tensor(target_btc_f[seq_length-1:-test_l])
X_tst = torch.Tensor(sequences[-test_l:,:,:])
y_tst = torch.Tensor(target_btc_f[-test_l:])

In [ ]:
X_tst.shape

In [ ]:
import torch
import torch.nn as nn

class TransformerClassifier(nn.Module):
    def __init__(self, input_dim, num_classes, d_model=128, num_heads=8, num_layers=4, dropout=0.1):
        super(TransformerClassifier, self).__init__()
        self.d_model = d_model
        
        # Input Embedding
        self.embedding = nn.Linear(input_dim, d_model)
        self.positional_encoding = self._generate_positional_encoding(max_len=5000, d_model=d_model)
        
        # Transformer Encoder
        self.encoder_layer = nn.TransformerEncoderLayer(d_model=d_model, nhead=num_heads, dropout=dropout)
        self.encoder = nn.TransformerEncoder(self.encoder_layer, num_layers=num_layers)
        
        # Classification Head
        self.classifier = nn.Sequential(
            nn.Linear(d_model, 64),
            nn.ReLU(),
            nn.Dropout(dropout),
            nn.Linear(64, num_classes)
        )
    
    def forward(self, x):
        # x: shape (batch_size, seq_len, input_dim)
        batch_size, seq_len, input_dim = x.shape
        
        # Embed input features
        x = self.embedding(x)  # shape: (batch_size, seq_len, d_model)
        
        # Add positional encoding
        x = x + self.positional_encoding[:seq_len, :].unsqueeze(0)
        
        # Permute for transformer: (seq_len, batch_size, d_model)
        x = x.permute(1, 0, 2)
        
        # Pass through the transformer encoder
        x = self.encoder(x)  # shape: (seq_len, batch_size, d_model)
        
        # Aggregate sequence output (e.g., take the mean)
        x = x.mean(dim=0)  # shape: (batch_size, d_model)
        
        # Classification
        out = self.classifier(x)  # shape: (batch_size, num_classes)
        return out
    
    def _generate_positional_encoding(self, max_len, d_model):
        # Positional encoding following "Attention is All You Need"
        pe = torch.zeros(max_len, d_model)
        position = torch.arange(0, max_len, dtype=torch.float).unsqueeze(1)
        div_term = torch.exp(torch.arange(0, d_model, 2).float() * -(torch.log(torch.tensor(10000.0)) / d_model))
        pe[:, 0::2] = torch.sin(position * div_term)
        pe[:, 1::2] = torch.cos(position * div_term)
        return pe

# Parameters
input_dim = 73  # 72 indicators + price
num_classes = 2  # Example: 5 classes for classification

# Initialize the model
model = TransformerClassifier(input_dim=input_dim, num_classes=num_classes)



In [ ]:
criterion = nn.CrossEntropyLoss()  # For multi-class classification
optimizer = torch.optim.Adam(model.parameters(), lr=0.001)

In [ ]:


num_epochs = 100

# Training loop
for epoch in range(num_epochs):
    model.train()  # Set the model to training mode

    # Zero the gradientsj
    optimizer.zero_grad()

    # Forward pass
    outputs = model(X_tr)  # Shape: (batch_size, num_classes)
    
    # Compute the loss
    loss = criterion(outputs, y_tr)
    
    # Backward pass (compute gradients)
    loss.backward()

    # Optimizer step (update model parameters)
    optimizer.step()

    # Print training progress
    if (epoch + 1) % 2 == 0:  # Print every 2 epochs
        print(f"Epoch [{epoch+1}/{num_epochs}], Loss: {loss.item():.4f}")

In [3]:
import numpy as np
def norm_mts_with_window(data, window_size=30):
    """
    Normalize a multivariate time series so that each component of the vector has
    a standard deviation of 1 within a sliding window lokking back in time.
    If window size is 1 does nothing.

    Returns np.array normalized time series data with the same shape as input.
    """
    t_steps, _ = data.shape
    normalized_data = np.zeros_like(data)

    for t in range(t_steps):
        start_i = max(0, t - window_size + 1)
        end_i = t + 1
        window = data[start_i:end_i]
        std = np.std(window, axis=0)
        mean = np.mean(window, axis=0)
        std[std == 0] = 1
        normalized_data[t] = (data[t])/ std

    return normalized_data
def create_seq_from_ts(data, seq_length):
    """
    Function that returns the vectors with corresponding seq_length,
    of observations in the past.

    Output should have shape (data.shape[0] - seq_length, seq_length, num_features)

    """
    sequences = []

    for i in range(len(data) - seq_length + 1):
        # Extract the sequence of features
        sequence = data[i:i+seq_length]
        sequences.append(sequence)

    sequences = np.array(sequences)
    return sequences


In [6]:
import numpy as np
import torch
seq_length = 30
val_perc = 0.1
test_perc = 0.5
data = np.load("few_series/np_series_concat2.npy")
def prepare_data(data):
    '''This function put the data into three different arrays,
    respectively train, validation and test. Keeping the Easliest data for testing and 
    the further in time data for training.
    retuns: (data_training(x,y), data_validation(x,y), data_testing(x,y))
    '''
    data_tr_x, data_val_x, data_tst_x = [], [], [] 
    data_tr_y, data_val_y, data_tst_y = [], [], []
    
    for j in range(data.shape[0]):  
        xdata = data[j, -1500:,:] #take only the last 1500 measurements
        data_2_norm = xdata[:, :-1]

        # Check for NaNs
        if np.isnan(data_2_norm).any().any():
            print(f"Something wrong at {j}")
            continue
        
        data_2_norm = norm_mts_with_window(data_2_norm)

        # Create sequences
        sequences = create_seq_from_ts(data_2_norm, seq_length)
        if np.isnan(sequences).any().any():
            print(f"Something wrong at sequences in {j}")
            continue

        # Prepare targets
        y = xdata[seq_length - 1:, -1]

        # Split into training, validation, and testing
        val_i = int(sequences.shape[0] * val_perc)
        test_i = int(sequences.shape[0] * test_perc)
        X_tr, X_val, X_tst = sequences[:-(val_i + test_i), :, :], sequences[-(val_i + test_i):-test_i, :, :], sequences[-test_i:, :, :]
        y_tr, y_val, y_tst = y[:-(val_i + test_i)], y[-(val_i + test_i):-test_i], y[-test_i:]
        y_val = (y_val + 1) / 2 
        y_tr = (y_tr + 1) / 2
        y_tst = (y_tst + 1) / 2  
        n_pos_tr = y_tr.sum()
        weight = (len(y_tr) -n_pos_tr)/n_pos_tr
        data_tr_x.append(X_tr)
        data_val_x.append(X_val)
        data_tst_x.append(X_tst)
        data_tr_y.append(y_tr)
        data_val_y.append(y_val)
        data_tst_y.append(y_tst)
    data_tr_x = np.concatenate(data_tr_x, axis=0)
    data_val_x = np.concatenate(data_val_x, axis=0) 
    data_tst_x = np.concatenate(data_tst_x, axis=0) 
    data_tr_y = np.concatenate(data_tr_y, axis=0)
    data_val_y = np.concatenate(data_val_y, axis=0) 
    data_tst_y = np.concatenate(data_tst_y, axis=0)  
    return ((data_tr_x, data_tr_y), 
            (data_val_x, data_val_y),
            (data_tst_x, data_tst_y))
    
def shuffle_data(X_data, y_data):
    """ With an input tensor (X,y) returns the tensor keeping X-y relations
        with the indices shuffled
    """     
    n_samples = X_data.size(0)
    indices = torch.randperm(n_samples)
    X_shuffled = X_data[indices]
    y_shuffled = y_data[indices]
    return X_shuffled, y_shuffled
data_res = prepare_data(data)   
print(" data tr x shape :", data_res[0][0].shape)
print(" data tr y shape :", data_res[0][1].shape)

print(" data val x shape :", data_res[1][0].shape)
print(" data val y shape :", data_res[1][1].shape)
print(" data sts x shape :", data_res[2][0].shape)
print(" data tst y shape :", data_res[2][1].shape)
X_tr_tensor = torch.Tensor(data_res[0][0])
y_tr_tensor = torch.Tensor(data_res[0][1])
X_shuffled, y_shuffled = shuffle_data(X_tr_tensor, y_tr_tensor)  
print(" \n shuffled x data shape ", X_shuffled.shape)
print(" \n shuffled y data shape ", y_shuffled.shape) 





Something wrong at 12
 data tr x shape : (11780, 30, 145)
 data tr y shape : (11780,)
 data val x shape : (2940, 30, 145)
 data val y shape : (2940,)
 data sts x shape : (14700, 30, 145)
 data tst y shape : (14700,)
 
 shuffled x data shape  torch.Size([11780, 30, 145])
 
 shuffled y data shape  torch.Size([11780])


In [17]:
torch.sum(y_shuffled).item() / y_shuffled.size(0)

0.5275891341256367

In [32]:
import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

# Example data: (n_samples, n_series, seq_len)
n_samples = 29420 # Number of samples
n_series = 145    # Number of time series per sample
seq_len = 30      # Length of each time series

# Simulated multivariate time series data
       # Binary labels

# Step 1: Flatten each sample (n_samples, n_series * seq_len)
X_flat = x_data.reshape(n_samples, -1)

# Step 2: Standardize features
scaler = StandardScaler()
X_flat = scaler.fit_transform(X_flat)

# Step 3: Split data into training and validation sets
X_train, X_val, y_train, y_val = train_test_split(X_flat, y_data, test_size=0.2, random_state=42)

# Step 4: Train L1-regularized Logistic Regression
lasso_logistic = LogisticRegression(
    penalty='l1', 
    solver='saga',  # 'saga' supports L1 regularization
    C=1.0,          # Regularization strength (inverse of lambda, tune as needed)
    max_iter=1000
)
lasso_logistic.fit(X_train, y_train)

# Step 5: Inspect coefficients
coefficients = lasso_logistic.coef_[0]  # Coefficients for the first (binary) class

# Identify non-zero coefficients
selected_features = np.where(coefficients != 0)[0]
print(f"Selected features (non-zero coefficients): {selected_features}")
print(f"Number of selected features: {len(selected_features)}")

# Step 6: Map selected features back to time series
selected_series = np.unique(selected_features // seq_len)
print(f"Selected time series indices: {selected_series}")
print(f"Number of selected time series: {len(selected_series)}")

Selected features (non-zero coefficients): [   0    1    2 ... 4347 4348 4349]
Number of selected features: 4219
Selected time series indices: [  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53
  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71
  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89
  90  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107
 108 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125
 126 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143
 144]
Number of selected time series: 145


/Users/carlos/miniconda3/envs/timeseries/lib/python3.10/site-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(


In [26]:
#features = [v[0] for v in scores_dic.items() if v[1]>0.005]
len(features)

31

In [30]:
##cell to add the normalized data into a single np array of shape (n_samples, 73)
seq_length = 30
import numpy as np
def norm_mts_with_window(data, window_size=30):
    """
    Normalize a multivariate time series so that each component of the vector has
    a standard deviation of 1 within a sliding window lokking back in time.
    If window size is 1 does nothing.

    Returns np.array normalized time series data with the same shape as input.
    """
    t_steps, _ = data.shape
    normalized_data = np.zeros_like(data)

    for t in range(t_steps):
        start_i = max(0, t - window_size + 1)
        end_i = t + 1
        window = data[start_i:end_i]
        std = np.std(window, axis=0)
        mean = np.mean(window, axis=0)
        std[std == 0] = 1
        normalized_data[t] = (data[t])/ std

    return normalized_data
series=data #np.load('/Users/carlos/Documents/Peccala/deepL_tests/few_series/np_series_concat2.npy')
x_data = []
y_data = []
for i in range(series.shape[0]):
    xdata= series[i, -1500:,:] #restrict to last 3000 measurements, do not include histograms, first
    #histograms are the first 72 features
    data_2_norm = xdata[: ,: -1]

    if np.isnan(data_2_norm).any().any():
        print(f"Something wrong at {i}")
        continue
    data_2_norm = norm_mts_with_window(data_2_norm)
    sequences = create_seq_from_ts(data_2_norm, seq_length)
    x_data.append(sequences)
    y_data.append( xdata[seq_length - 1:, -1])
x_data = np.concatenate(x_data, axis=0)    
y_data = np.concatenate(y_data, axis=0)   
print(f"resulting x shape {x_data.shape}" )    
print(f"resulting y shape {y_data.shape}" )    


Something wrong at 12
resulting x shape (29420, 30, 145)
resulting y shape (29420,)


In [2]:
import numpy as np
series=np.load('/Users/carlos/Documents/Peccala/deepL_tests/few_series/np_series_concat2.npy')
x_data = []
y_data = []
for i in range(series.shape[0]):
    xdata= series[i, -3000:,72:]

In [10]:

    

x=create_seq_from_ts(xdata, seq_length=3)
print(np.isnan(x).any().any())

False


In [34]:
tst_i=int(y_data.shape[0]*0.15)
tst_i2 = int(y_data.shape[0]*0.05)
tr_x =x_data[:-tst_i]
tst_x=x_data[-tst_i:-tst_i2]
tr_y = y_data[:-tst_i]
tst_y= y_data[-tst_i:-tst_i2]
print(f" for tr sum {sum(tr_y)} of {len(tr_y)} samples ")
print(f" for tst sum {sum(tst_y)} of {len(tst_y)} samples ")

 for tr sum -1338.0 of 40800 samples 
 for tst sum 230.0 of 4800 samples 


In [36]:
!pip install imbalanced-learn
from imblearn.over_sampling import SMOTE

smote = SMOTE(random_state=42)
X_resampled, y_resampled = smote.fit_resample(tr_x, tr_y)

/Users/carlos/miniconda3/envs/timeseries/lib/python3.10/site-packages/sklearn/base.py:474: FutureWarning: `BaseEstimator._validate_data` is deprecated in 1.6 and will be removed in 1.7. Use `sklearn.utils.validation.validate_data` instead. This function becomes public and is part of the scikit-learn developer API.
  warnings.warn(
/Users/carlos/miniconda3/envs/timeseries/lib/python3.10/site-packages/sklearn/utils/_tags.py:354: FutureWarning: The SMOTE or classes from which it inherits use `_get_tags` and `_more_tags`. Please define the `__sklearn_tags__` method, or inherit from `sklearn.base.BaseEstimator` and/or other appropriate mixins such as `sklearn.base.TransformerMixin`, `sklearn.base.ClassifierMixin`, `sklearn.base.RegressorMixin`, and `sklearn.base.OutlierMixin`. From scikit-learn 1.7, not defining `__sklearn_tags__` will raise an error.
  warnings.warn(


In [68]:
import pandas as pd
#df = pd.DataFrame(x_data)

#correlation_matrix = df.corr()

#print("Correlation Matrix:")
count = 0
for i in range(len(correlation_matrix)-1):
    c = max(correlation_matrix[i][i+1:])
    if c > 0.88:
        print(f" {c} max corr at {i}")
        count +=1
print("final count ", count)        


 0.9108953283884931 max corr at 15
 0.9297958729793113 max corr at 17
 0.961457710222429 max corr at 19
 0.9606166467335108 max corr at 20
 0.9299131427871605 max corr at 21
 0.9223859242882432 max corr at 22
 0.9351430421910194 max corr at 23
 0.9389277325163841 max corr at 24
 0.9658937041107518 max corr at 25
 0.9297472796672076 max corr at 26
 0.9151739734110896 max corr at 27
 0.8809021727584668 max corr at 28
 0.9678563677641636 max corr at 31
 0.9565679942440866 max corr at 32
 0.9284400874443614 max corr at 33
 0.9416147684493164 max corr at 34
 0.9541464179740394 max corr at 35
 0.9361678945548246 max corr at 36
 0.9387799029504377 max corr at 37
 0.8915745310356116 max corr at 38
 0.9271048847729666 max corr at 42
 0.9313561657965201 max corr at 43
 0.9655884837392488 max corr at 44
 0.9767924619733681 max corr at 45
 0.9690411846960109 max corr at 46
 0.9064103296264922 max corr at 47
 0.9359281740376326 max corr at 49
 0.946175821527798 max corr at 50
 0.9569045257280056 ma

In [20]:
import numpy as np

def norm_mts_with_window(data, window_size=30):
    """
    Normalize a multivariate time series so that each component of the vector has
    a standard deviation of 1 within a sliding window lokking back in time.
    If window size is 1 does nothing.

    Returns np.array normalized time series data with the same shape as input.
    """
    t_steps, _ = data.shape
    normalized_data = np.zeros_like(data)

    for t in range(t_steps):
        start_i = max(0, t - window_size + 1)
        end_i = t + 1
        window = data[start_i:end_i]
        std = np.std(window, axis=0)
        mean = np.mean(window, axis=0)
        std[std == 0] = 1
        normalized_data[t] = (data[t])/ std

    return normalized_data


#function to create tensor with seg_length of backward steps
def create_seq_from_ts(data, seq_length):
    """
    Function that returns the vectors with corresponding seq_length,
    of observations in the past.

    Output should have shape (data.shape[0] - seq_length, seq_length, num_features)

    """
    sequences = []

    for i in range(len(data) - seq_length + 1):
        # Extract the sequence of features
        sequence = data[i:i+seq_length]
        sequences.append(sequence)

    sequences = np.array(sequences)
    return sequences
    

x=np.array([[1,3,3], [2,2,3], [3,3,3],[1,0,3]])
y=create_seq_from_ts(x, seq_length=2) 
print(y)


[[[1 3 3]
  [2 2 3]]

 [[2 2 3]
  [3 3 3]]

 [[3 3 3]
  [1 0 3]]]


In [1]:
import numpy as np
a=np.array([1,0,1])
print(a.sum())

2


In [3]:
a = [1,2,4]
a.pop(2)
print(a)

[1, 2]


In [ ]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from skfda.representation.basis import FourierBasis
from skfda.preprocessing.dim_reduction.feature_extraction import FPCA
from sklearn.linear_model import LogisticRegression

# Example: multivariate time series
# data: (n_samples, n_timepoints, n_features)
n_samples, n_timepoints, n_features = 100, 50, 3
data = np.random.randn(n_samples, n_timepoints, n_features)
labels = np.random.randint(0, 2, n_samples)

# Transform each feature into functional data
basis = FourierBasis(n_basis=10, domain_range=(0, n_timepoints))
fd_list = [basis.fit_transform(data[:, :, i]) for i in range(n_features)]

# Combine into multivariate functional data
from skfda.representation.grid import FDataGrid
combined_fd = FDataGrid(data_matrix=np.stack(fd_list, axis=-1))

# Apply fMPCA
fpca = FPCA(n_components=5)  # Retain 5 components
reduced_data = fpca.fit_transform(combined_fd)

# Train-test split
X_train, X_test, y_train, y_test = train_test_split(reduced_data, labels, test_size=0.2, random_state=42)

# Train classifier
clf = LogisticRegression()
clf.fit(X_train, y_train)
accuracy = clf.score(X_test, y_test)
print(f"Classification accuracy: {accuracy * 100:.2f}%")


In [13]:
aux=txt.split('val acc')[1:]
print([float(i.split(',')[0].replace(":",'')) for i in aux])

[55.847100745059926, 56.85131195335277, 53.806284418529316, 53.48234531908001, 62.45545837382572, 60.349854227405245, 57.142857142857146, 54.81049562682216, 57.33722060252673, 54.84288953676709, 58.082280531260125, 58.63297700032394, 57.24003887269193, 57.175251052802075, 52.445740200842245, 58.73015873015873, 57.07806932296728]


In [ ]:
print(str({1:[1,2,3]}))

{1: [1, 2, 3]}


: 